# Generated by Django 4.1.3 on 2022-11-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc_details',
            name='more_button',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
