# Generated by Django 4.1.3 on 2022-11-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_pc_details_more_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc_details',
            name='description_1',
            field=models.TextField(null=True),
        ),
    ]
